apiVersion: batch/v1
kind: Job
metadata:
  name: k6-load-test
spec:
  template:
    spec:
      containers:
      - name: k6
        image: loadimpact/k6
        command: ["k6", "run", "-"]
        stdin: true
        stdinOnce: true
        tty: true
        volumeMounts:
        - name: k6-test
          mountPath: /test
      restartPolicy: Never
      volumes:
      - name: k6-test
        configMap:
          name: k6-test-script
  backoffLimit: 4